repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
{% if cookiecutter.black %}
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
{% endif %}
{% if cookiecutter.blacken_docs %}
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.3.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: black
{% endif %}
{% if cookiecutter.isort %}
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.2
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
    -   id: isort
{% endif %}

